### ISSUE TITLE
Get activity state API issue 

### ISSUE THREAD

**Issue by kienv** [Brightcookie/lxHive#22] opened 2015-08-14 13:27 UTC
Get activity state API is getting "Access-Control-Allow-Origin" error issue

POST https://api.experience.at/activities/state?method=GET 
quiz.html:1 XMLHttpRequest cannot load https://api.experience.at/activities/state?method=GET. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mygpcommunity.com.au' is therefore not allowed access. The response had HTTP status code 500.

**Comment by RoboSparrow** [comment] 2015-08-16 21:37
Not sure what the issue is, it seems to work ok in the tests. You have to include the CORS header on your request. Maybe we need to check the legacy mode

**Comment by sraka1** [comment] 2015-08-16 21:38
This was handled in the development branch with 469fcf6d895fdea81172983849bf0936919c084d, however I still need to test it.

**Comment by RoboSparrow** [comment] 2015-08-20 23:06
related to #23

**Comment by sraka1** [comment] 2015-08-24 04:45
Fix confirmed, closing. Please re-open if you're still getting the issue.

**Closed by sraka1** 2015-08-24 04:45 UTC
Labels: bug
